# Generated by Django 3.1.6 on 2021-02-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210215_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shippingCost',
            field=models.FloatField(null=True),
        ),
    ]
